package com.qsp.employee.enums;

public enum Authority {
	
	 VIEW_USER,
	    DELETE_USER,
	    CREATE_USER,
	    UPDATE_USER,
	    VIEW_DEPARTMENT,
	    DELETE_DEPARTMENT,
	    CREATE_DEPARTMENT,
	    UPDATE_DEPARTMENT,
	    VIEW_PROJECT,
	    DELETE_PROJECT,
	    CREATE_PROJECT,
	    UPDATE_PROJECT,
	    VIEW_TASK,
	    DELETE_TASK,
	    CREATE_TASK,
	    UPDATE_TASK

}
